---
version: 1

kind: experiment

framework: pytorch

build:
   image: pytorch/pytorch:1.1.0-cuda10.0-cudnn7.5-runtime # Image name to use
   build_steps:
      - pip install -r requirements.txt
environment:
 resources:
   cpu:
     requests: 4
     limits: 8 
   memory:
     requests: 8192
     limits: 8192
   gpu:
     requests: 1
     limits: 1
params:
  epochs: 10
  batch_size: 15
  lr: 0.001
  save_cp: False
  gpu: True
  notifications: True
  polyaxon: True
  expositions: 15
  tensorb: True
  #img_scale:
  #momentum: 0.9
  #log_interval: 100
  #batch_size_test: 15
  #val_percent=0.20,
              

run:
  cmd: python ushdrcnn_train.py  --epochs={{ epochs }} \
                        --batch-size={{ batch_size }} \
                         --lr={{ lr }} \
                         --expo-num={{expositions}} \
                         --save_cp={{ save_cp }} \
                         --polyaxon={{ polyaxon }} \
                         --gpu={{ gpu }} \
                         --notifications={{ notifications }} \
                         --tensorboard={{tensorb}}

