---
version: 1

kind: experiment

framework: pytorch

build:
   image: pytorch/pytorch:1.1.0-cuda10.0-cudnn7.5-runtime # Image name to use
   build_steps:
      - apt update
      - apt install -y libglib2.0-0 libsm6 libxext6 libxrender-dev 
      - pip install opencv-python
      - pip install -r requirements.txt 

environment:
 resources:
   cpu:
     requests: 4
     limits: 8 
   memory:
     requests: 8192
     limits: 8192
   gpu:
     requests: 1
     limits: 1
params:
  epochs: 10
  batch_size: 15
  lr: 0.00001
  save: False
  gpu: True
  notifications: True
  polyaxon: True
  expositions: 15
  tensor_b: True
  checkpoint: $POLYAXON_RUN_OUTPUTS_PATH
  #img_scale:
  #momentum: 0.9
  #log_interval: 100
  #batch_size_test: 15
  #val_percent=0.20,
              

run:
  cmd: python -u ushdrcnn_train.py  --epochs={{ epochs }} \
                        --batch-size={{ batch_size }} \
                         --learning-rate={{ lr }} \
                         --expo-num={{expositions}} \
                         --outputs-path=$POLYAXON_RUN_OUTPUTS_PATH \ 
                         -p \
                         -g \
                         -n \
                         -t 
                         #-m

